# Generated by Django 3.2.5 on 2021-11-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_Donor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=4)),
                ('qty', models.CharField(max_length=4)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
            ],
        ),
    ]
